Implement finish function

diff --git a/bootloader_unlocker b/bootloader_unlocker
--- a/bootloader_unlocker
+++ b/bootloader_unlocker
@@ -1,4 +1,11 @@
 #!/bin/bash
+# Cleanup funcion
+function finish {
+  # Your cleanup code here
+  echo "Saving..."
+  echo "${value}" > ${devfile}
+}
+trap finish EXIT
 # get the current device name
 devices=(`fastboot devices`);
 device=${devices[0]}
@@ -14,14 +21,11 @@ else
 fi
 # while [ $value -le 5 ]
 # do
-	# # show it to the user
-	# echo "Trying: ${value}"
+	# show it to the user
+	echo "Trying: ${value}"
 	# fastboot oem unlock $value
-	# # increment the value
-	# value=`evaluepr ${value} + 1`
-	# # and save it for nevaluet time
+	# increment the value
+	value=$((value+1));
+	# and save it for nevaluet time
 	# echo "${value}" > /tmp/value.dat
-# done
-echo "${value}"
-value=$((value+1))
-echo "${value}" > ${devfile}
+# done;
